# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'halfcellinterface.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QGroupBox,
    QLabel, QLineEdit, QPushButton, QRadioButton,
    QSizePolicy, QTabWidget, QTextBrowser, QTextEdit,
    QWidget)

class Ui_HalfCellInterface(object):
    def setupUi(self, HalfCellInterface):
        if not HalfCellInterface.objectName():
            HalfCellInterface.setObjectName(u"HalfCellInterface")
        HalfCellInterface.resize(950, 640)
        self.half_return_Button = QPushButton(HalfCellInterface)
        self.half_return_Button.setObjectName(u"half_return_Button")
        self.half_return_Button.setGeometry(QRect(840, 590, 91, 31))
        font = QFont()
        font.setPointSize(12)
        self.half_return_Button.setFont(font)
        self.textBrowser = QTextBrowser(HalfCellInterface)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(0, 0, 410, 130))
        self.terminal_output_window = QTextEdit(HalfCellInterface)
        self.terminal_output_window.setObjectName(u"terminal_output_window")
        self.terminal_output_window.setGeometry(QRect(0, 140, 410, 300))
        self.command_input_lineEdit = QLineEdit(HalfCellInterface)
        self.command_input_lineEdit.setObjectName(u"command_input_lineEdit")
        self.command_input_lineEdit.setGeometry(QRect(0, 460, 291, 25))
        self.tabWidget = QTabWidget(HalfCellInterface)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(430, 0, 521, 581))
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.unit_select_box = QComboBox(self.tab)
        self.unit_select_box.addItem("")
        self.unit_select_box.addItem("")
        self.unit_select_box.addItem("")
        self.unit_select_box.setObjectName(u"unit_select_box")
        self.unit_select_box.setGeometry(QRect(20, 40, 161, 25))
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 10, 111, 21))
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(230, 180, 81, 17))
        self.length_lineEdit = QLineEdit(self.tab)
        self.length_lineEdit.setObjectName(u"length_lineEdit")
        self.length_lineEdit.setGeometry(QRect(110, 130, 81, 25))
        self.width_lineEdit = QLineEdit(self.tab)
        self.width_lineEdit.setObjectName(u"width_lineEdit")
        self.width_lineEdit.setGeometry(QRect(110, 180, 81, 25))
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 180, 71, 17))
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 90, 221, 17))
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 130, 101, 17))
        self.height_lineEdit = QLineEdit(self.tab)
        self.height_lineEdit.setObjectName(u"height_lineEdit")
        self.height_lineEdit.setGeometry(QRect(340, 180, 81, 25))
        self.length2_lineEdit = QLineEdit(self.tab)
        self.length2_lineEdit.setObjectName(u"length2_lineEdit")
        self.length2_lineEdit.setGeometry(QRect(340, 130, 81, 25))
        self.z_divide_lineEdit = QLineEdit(self.tab)
        self.z_divide_lineEdit.setObjectName(u"z_divide_lineEdit")
        self.z_divide_lineEdit.setGeometry(QRect(160, 330, 81, 25))
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 280, 16, 17))
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 330, 16, 17))
        self.label_10 = QLabel(self.tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(130, 330, 16, 17))
        self.x_divide_lineEdit = QLineEdit(self.tab)
        self.x_divide_lineEdit.setObjectName(u"x_divide_lineEdit")
        self.x_divide_lineEdit.setGeometry(QRect(30, 280, 81, 25))
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 240, 261, 17))
        self.y_divide_lineEdit = QLineEdit(self.tab)
        self.y_divide_lineEdit.setObjectName(u"y_divide_lineEdit")
        self.y_divide_lineEdit.setGeometry(QRect(30, 330, 81, 25))
        self.change_geometry_button = QPushButton(self.tab)
        self.change_geometry_button.setObjectName(u"change_geometry_button")
        self.change_geometry_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_geometry_button = QPushButton(self.tab)
        self.run_geometry_button.setObjectName(u"run_geometry_button")
        self.run_geometry_button.setGeometry(QRect(410, 510, 89, 25))
        self.label_31 = QLabel(self.tab)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(230, 130, 91, 17))
        self.label_34 = QLabel(self.tab)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(130, 280, 21, 17))
        self.x2_divide_lineEdit = QLineEdit(self.tab)
        self.x2_divide_lineEdit.setObjectName(u"x2_divide_lineEdit")
        self.x2_divide_lineEdit.setGeometry(QRect(160, 280, 81, 25))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 20, 121, 21))
        self.label_11.setFont(font)
        self.CeWE_lineEdit = QLineEdit(self.tab_2)
        self.CeWE_lineEdit.setObjectName(u"CeWE_lineEdit")
        self.CeWE_lineEdit.setGeometry(QRect(20, 50, 113, 25))
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 90, 111, 21))
        self.label_12.setFont(font)
        self.Cesp_lineEdit = QLineEdit(self.tab_2)
        self.Cesp_lineEdit.setObjectName(u"Cesp_lineEdit")
        self.Cesp_lineEdit.setGeometry(QRect(20, 120, 113, 25))
        self.label_13 = QLabel(self.tab_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 160, 101, 21))
        self.label_13.setFont(font)
        self.fWE_lineEdit = QLineEdit(self.tab_2)
        self.fWE_lineEdit.setObjectName(u"fWE_lineEdit")
        self.fWE_lineEdit.setGeometry(QRect(20, 190, 113, 25))
        self.label_14 = QLabel(self.tab_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 230, 181, 21))
        self.label_14.setFont(font)
        self.label_15 = QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 300, 101, 17))
        self.label_15.setFont(font)
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 370, 161, 17))
        self.label_16.setFont(font)
        self.maxWE_lineEdit = QLineEdit(self.tab_2)
        self.maxWE_lineEdit.setObjectName(u"maxWE_lineEdit")
        self.maxWE_lineEdit.setGeometry(QRect(20, 260, 113, 25))
        self.R_lineEdit = QLineEdit(self.tab_2)
        self.R_lineEdit.setObjectName(u"R_lineEdit")
        self.R_lineEdit.setGeometry(QRect(20, 400, 113, 25))
        self.brugg_lineEdit = QLineEdit(self.tab_2)
        self.brugg_lineEdit.setObjectName(u"brugg_lineEdit")
        self.brugg_lineEdit.setGeometry(QRect(20, 330, 113, 25))
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(210, 20, 121, 17))
        self.label_17.setFont(font)
        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(210, 90, 151, 21))
        self.label_18.setFont(font)
        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(210, 160, 141, 21))
        self.label_19.setFont(font)
        self.D0Ce_lineEdit = QLineEdit(self.tab_2)
        self.D0Ce_lineEdit.setObjectName(u"D0Ce_lineEdit")
        self.D0Ce_lineEdit.setGeometry(QRect(210, 190, 113, 25))
        self.faisWE_lineEdit = QLineEdit(self.tab_2)
        self.faisWE_lineEdit.setObjectName(u"faisWE_lineEdit")
        self.faisWE_lineEdit.setGeometry(QRect(210, 120, 113, 25))
        self.tNo_lineEdit = QLineEdit(self.tab_2)
        self.tNo_lineEdit.setObjectName(u"tNo_lineEdit")
        self.tNo_lineEdit.setGeometry(QRect(210, 50, 113, 25))
        self.run_constant_button = QPushButton(self.tab_2)
        self.run_constant_button.setObjectName(u"run_constant_button")
        self.run_constant_button.setGeometry(QRect(410, 510, 89, 25))
        self.help_constant_button = QPushButton(self.tab_2)
        self.help_constant_button.setObjectName(u"help_constant_button")
        self.help_constant_button.setGeometry(QRect(410, 470, 89, 25))
        self.F_lineEdit = QLineEdit(self.tab_2)
        self.F_lineEdit.setObjectName(u"F_lineEdit")
        self.F_lineEdit.setGeometry(QRect(20, 470, 113, 25))
        self.label_32 = QLabel(self.tab_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 440, 151, 17))
        self.label_32.setFont(font)
        self.rs_lineEdit = QLineEdit(self.tab_2)
        self.rs_lineEdit.setObjectName(u"rs_lineEdit")
        self.rs_lineEdit.setGeometry(QRect(210, 260, 113, 25))
        self.label_33 = QLabel(self.tab_2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(210, 230, 111, 21))
        self.label_33.setFont(font)
        self.DsWE_lineEdit = QLineEdit(self.tab_2)
        self.DsWE_lineEdit.setObjectName(u"DsWE_lineEdit")
        self.DsWE_lineEdit.setGeometry(QRect(210, 330, 113, 25))
        self.label_35 = QLabel(self.tab_2)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(210, 300, 141, 21))
        self.label_35.setFont(font)
        self.KReact_lineEdit = QLineEdit(self.tab_2)
        self.KReact_lineEdit.setObjectName(u"KReact_lineEdit")
        self.KReact_lineEdit.setGeometry(QRect(210, 400, 113, 25))
        self.label_36 = QLabel(self.tab_2)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(210, 370, 241, 21))
        self.label_36.setFont(font)
        self.label_45 = QLabel(self.tab_2)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(210, 440, 241, 21))
        self.label_45.setFont(font)
        self.KReactRE_lineEdit = QLineEdit(self.tab_2)
        self.KReactRE_lineEdit.setObjectName(u"KReactRE_lineEdit")
        self.KReactRE_lineEdit.setGeometry(QRect(210, 470, 113, 25))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.run_constant2_button = QPushButton(self.tab_6)
        self.run_constant2_button.setObjectName(u"run_constant2_button")
        self.run_constant2_button.setGeometry(QRect(410, 510, 89, 25))
        self.change_constant_button = QPushButton(self.tab_6)
        self.change_constant_button.setObjectName(u"change_constant_button")
        self.change_constant_button.setGeometry(QRect(410, 470, 89, 25))
        self.label_20 = QLabel(self.tab_6)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 360, 111, 21))
        self.label_20.setFont(font)
        self.label_38 = QLabel(self.tab_6)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(30, 100, 111, 21))
        self.label_38.setFont(font)
        self.alphaCWE_lineEdit = QLineEdit(self.tab_6)
        self.alphaCWE_lineEdit.setObjectName(u"alphaCWE_lineEdit")
        self.alphaCWE_lineEdit.setGeometry(QRect(30, 130, 113, 25))
        self.select_discharge = QRadioButton(self.tab_6)
        self.select_discharge.setObjectName(u"select_discharge")
        self.select_discharge.setGeometry(QRect(30, 420, 112, 23))
        self.groupBox = QGroupBox(self.tab_6)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(210, 30, 121, 101))
        self.select_carbon = QRadioButton(self.groupBox)
        self.select_carbon.setObjectName(u"select_carbon")
        self.select_carbon.setGeometry(QRect(10, 30, 112, 23))
        self.select_silicon = QRadioButton(self.groupBox)
        self.select_silicon.setObjectName(u"select_silicon")
        self.select_silicon.setGeometry(QRect(10, 70, 112, 23))
        self.select_charge = QRadioButton(self.tab_6)
        self.select_charge.setObjectName(u"select_charge")
        self.select_charge.setGeometry(QRect(30, 390, 112, 23))
        self.I_lineEdit = QLineEdit(self.tab_6)
        self.I_lineEdit.setObjectName(u"I_lineEdit")
        self.I_lineEdit.setGeometry(QRect(30, 450, 113, 25))
        self.alphaAWE_lineEdit = QLineEdit(self.tab_6)
        self.alphaAWE_lineEdit.setObjectName(u"alphaAWE_lineEdit")
        self.alphaAWE_lineEdit.setGeometry(QRect(30, 50, 113, 25))
        self.label_37 = QLabel(self.tab_6)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(30, 20, 111, 21))
        self.label_37.setFont(font)
        self.alphaARE_lineEdit = QLineEdit(self.tab_6)
        self.alphaARE_lineEdit.setObjectName(u"alphaARE_lineEdit")
        self.alphaARE_lineEdit.setGeometry(QRect(30, 220, 113, 25))
        self.label_47 = QLabel(self.tab_6)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(30, 190, 111, 21))
        self.label_47.setFont(font)
        self.alphaCRE_lineEdit = QLineEdit(self.tab_6)
        self.alphaCRE_lineEdit.setObjectName(u"alphaCRE_lineEdit")
        self.alphaCRE_lineEdit.setGeometry(QRect(30, 300, 113, 25))
        self.label_48 = QLabel(self.tab_6)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(30, 270, 111, 21))
        self.label_48.setFont(font)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_21 = QLabel(self.tab_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 20, 181, 17))
        self.label_21.setFont(font)
        self.WE_ce_lineEdit = QLineEdit(self.tab_3)
        self.WE_ce_lineEdit.setObjectName(u"WE_ce_lineEdit")
        self.WE_ce_lineEdit.setGeometry(QRect(20, 50, 113, 25))
        self.change_boundary_button = QPushButton(self.tab_3)
        self.change_boundary_button.setObjectName(u"change_boundary_button")
        self.change_boundary_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_boundary_button = QPushButton(self.tab_3)
        self.run_boundary_button.setObjectName(u"run_boundary_button")
        self.run_boundary_button.setGeometry(QRect(410, 510, 89, 25))
        self.label_39 = QLabel(self.tab_3)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(20, 110, 181, 17))
        self.label_39.setFont(font)
        self.WE_cs_lineEdit = QLineEdit(self.tab_3)
        self.WE_cs_lineEdit.setObjectName(u"WE_cs_lineEdit")
        self.WE_cs_lineEdit.setGeometry(QRect(20, 140, 113, 25))
        self.WE_faie_lineEdit = QLineEdit(self.tab_3)
        self.WE_faie_lineEdit.setObjectName(u"WE_faie_lineEdit")
        self.WE_faie_lineEdit.setGeometry(QRect(20, 230, 113, 25))
        self.label_40 = QLabel(self.tab_3)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(20, 200, 211, 21))
        self.label_40.setFont(font)
        self.WE_fais_lineEdit = QLineEdit(self.tab_3)
        self.WE_fais_lineEdit.setObjectName(u"WE_fais_lineEdit")
        self.WE_fais_lineEdit.setGeometry(QRect(20, 320, 113, 25))
        self.label_41 = QLabel(self.tab_3)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(20, 290, 211, 21))
        self.label_41.setFont(font)
        self.sep_ce_lineEdit = QLineEdit(self.tab_3)
        self.sep_ce_lineEdit.setObjectName(u"sep_ce_lineEdit")
        self.sep_ce_lineEdit.setGeometry(QRect(210, 50, 113, 25))
        self.label_42 = QLabel(self.tab_3)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(210, 20, 211, 17))
        self.label_42.setFont(font)
        self.sep_faie_lineEdit = QLineEdit(self.tab_3)
        self.sep_faie_lineEdit.setObjectName(u"sep_faie_lineEdit")
        self.sep_faie_lineEdit.setGeometry(QRect(210, 140, 113, 25))
        self.label_43 = QLabel(self.tab_3)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(210, 110, 211, 21))
        self.label_43.setFont(font)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.change_function_button = QPushButton(self.tab_4)
        self.change_function_button.setObjectName(u"change_function_button")
        self.change_function_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_function_button = QPushButton(self.tab_4)
        self.run_function_button.setObjectName(u"run_function_button")
        self.run_function_button.setGeometry(QRect(410, 510, 89, 25))
        self.label_22 = QLabel(self.tab_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 20, 171, 17))
        self.label_22.setFont(font)
        self.label_23 = QLabel(self.tab_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 110, 101, 17))
        self.label_23.setFont(font)
        self.label_24 = QLabel(self.tab_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 200, 111, 17))
        self.label_24.setFont(font)
        self.label_25 = QLabel(self.tab_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 290, 121, 17))
        self.label_25.setFont(font)
        self.label_26 = QLabel(self.tab_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 380, 131, 17))
        self.interpolation_comboBox = QComboBox(self.tab_4)
        self.interpolation_comboBox.addItem("")
        self.interpolation_comboBox.addItem("")
        self.interpolation_comboBox.addItem("")
        self.interpolation_comboBox.setObjectName(u"interpolation_comboBox")
        self.interpolation_comboBox.setGeometry(QRect(20, 410, 221, 25))
        self.laplacian_comboBox = QComboBox(self.tab_4)
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.setObjectName(u"laplacian_comboBox")
        self.laplacian_comboBox.setGeometry(QRect(20, 320, 221, 25))
        self.gardient_comboBox = QComboBox(self.tab_4)
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.setObjectName(u"gardient_comboBox")
        self.gardient_comboBox.setGeometry(QRect(20, 140, 221, 25))
        self.derivative_comboBox = QComboBox(self.tab_4)
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.setObjectName(u"derivative_comboBox")
        self.derivative_comboBox.setGeometry(QRect(20, 50, 221, 25))
        self.divergence_comboBox = QComboBox(self.tab_4)
        self.divergence_comboBox.addItem("")
        self.divergence_comboBox.addItem("")
        self.divergence_comboBox.setObjectName(u"divergence_comboBox")
        self.divergence_comboBox.setGeometry(QRect(20, 230, 221, 25))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_27 = QLabel(self.tab_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(30, 20, 101, 17))
        self.tolerance_lineEdit = QLineEdit(self.tab_5)
        self.tolerance_lineEdit.setObjectName(u"tolerance_lineEdit")
        self.tolerance_lineEdit.setGeometry(QRect(30, 50, 113, 25))
        self.change_control_button = QPushButton(self.tab_5)
        self.change_control_button.setObjectName(u"change_control_button")
        self.change_control_button.setGeometry(QRect(388, 440, 111, 25))
        self.label_28 = QLabel(self.tab_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(240, 20, 121, 17))
        self.endtime_lineEdit = QLineEdit(self.tab_5)
        self.endtime_lineEdit.setObjectName(u"endtime_lineEdit")
        self.endtime_lineEdit.setGeometry(QRect(240, 50, 113, 25))
        self.label_29 = QLabel(self.tab_5)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(240, 100, 131, 17))
        self.timestep_lineEdit = QLineEdit(self.tab_5)
        self.timestep_lineEdit.setObjectName(u"timestep_lineEdit")
        self.timestep_lineEdit.setGeometry(QRect(240, 130, 113, 25))
        self.label_30 = QLabel(self.tab_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(240, 180, 251, 17))
        self.interval_lineEdit = QLineEdit(self.tab_5)
        self.interval_lineEdit.setObjectName(u"interval_lineEdit")
        self.interval_lineEdit.setGeometry(QRect(240, 210, 113, 25))
        self.run_button = QPushButton(self.tab_5)
        self.run_button.setObjectName(u"run_button")
        self.run_button.setGeometry(QRect(388, 480, 111, 25))
        self.pause_run_button = QPushButton(self.tab_5)
        self.pause_run_button.setObjectName(u"pause_run_button")
        self.pause_run_button.setGeometry(QRect(388, 520, 111, 25))
        self.tabWidget.addTab(self.tab_5, "")
        self.pushButton = QPushButton(HalfCellInterface)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(310, 460, 89, 25))
        self.label_44 = QLabel(HalfCellInterface)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 530, 151, 17))
        self.open_paraview_Button = QPushButton(HalfCellInterface)
        self.open_paraview_Button.setObjectName(u"open_paraview_Button")
        self.open_paraview_Button.setGeometry(QRect(170, 530, 89, 25))
        self.view_result_button = QPushButton(HalfCellInterface)
        self.view_result_button.setObjectName(u"view_result_button")
        self.view_result_button.setEnabled(False)
        self.view_result_button.setGeometry(QRect(170, 580, 89, 25))
        self.label_46 = QLabel(HalfCellInterface)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(10, 580, 141, 17))

        self.retranslateUi(HalfCellInterface)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(HalfCellInterface)
    # setupUi

    def retranslateUi(self, HalfCellInterface):
        HalfCellInterface.setWindowTitle(QCoreApplication.translate("HalfCellInterface", u"Dialog", None))
        self.half_return_Button.setText(QCoreApplication.translate("HalfCellInterface", u"Home", None))
        self.textBrowser.setHtml(QCoreApplication.translate("HalfCellInterface", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The module you choose is <span style=\" font-weight:600;\">HalfCell</span>. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The initial values shown in the input boxes and select boxs are the current values in the files.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you are the first time to run this project, you must click <span style=\" font-weight:600;\">*Modify</span> button on Geometry interfac"
                        "e at least once even if you do not change parameters on this interface. </p></body></html>", None))
        self.unit_select_box.setItemText(0, QCoreApplication.translate("HalfCellInterface", u"micrometer(um)", None))
        self.unit_select_box.setItemText(1, QCoreApplication.translate("HalfCellInterface", u"millimeter(mm)", None))
        self.unit_select_box.setItemText(2, QCoreApplication.translate("HalfCellInterface", u"meter(m)", None))

        self.label.setText(QCoreApplication.translate("HalfCellInterface", u"Length unit", None))
        self.label_5.setText(QCoreApplication.translate("HalfCellInterface", u"Height", None))
        self.label_4.setText(QCoreApplication.translate("HalfCellInterface", u"Width", None))
        self.label_2.setText(QCoreApplication.translate("HalfCellInterface", u"Computational domain", None))
        self.label_3.setText(QCoreApplication.translate("HalfCellInterface", u"Length_WE", None))
        self.label_8.setText(QCoreApplication.translate("HalfCellInterface", u"X", None))
        self.label_9.setText(QCoreApplication.translate("HalfCellInterface", u"Y", None))
        self.label_10.setText(QCoreApplication.translate("HalfCellInterface", u"Z", None))
        self.label_7.setText(QCoreApplication.translate("HalfCellInterface", u"Mesh settings", None))
        self.change_geometry_button.setText(QCoreApplication.translate("HalfCellInterface", u"*Modify", None))
        self.run_geometry_button.setText(QCoreApplication.translate("HalfCellInterface", u"Next", None))
        self.label_31.setText(QCoreApplication.translate("HalfCellInterface", u"Length_SEP", None))
        self.label_34.setText(QCoreApplication.translate("HalfCellInterface", u"X2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("HalfCellInterface", u"Geometry->", None))
        self.label_11.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>por<span style=\" vertical-align:sub;\">WE</span></p></body></html>", None))
        self.label_12.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>por<span style=\" vertical-align:sub;\">SEP</span></p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>por<span style=\" vertical-align:sub;\">f,WE</span></p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>C<span style=\" vertical-align:sub;\">s,max</span>(WE)(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_15.setText(QCoreApplication.translate("HalfCellInterface", u"brugg", None))
        self.label_16.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>R(J/(Mol*k))</p></body></html>", None))
        self.label_17.setText(QCoreApplication.translate("HalfCellInterface", u"tNo", None))
        self.label_18.setText(QCoreApplication.translate("HalfCellInterface", u"k<sub>0,WE</sub>(S/m)", None))
        self.label_19.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>D<span style=\" vertical-align:sub;\">0,e</span>(m<span style=\" vertical-align:super;\">2</span>/s)</p></body></html>", None))
        self.run_constant_button.setText(QCoreApplication.translate("HalfCellInterface", u"Next", None))
        self.help_constant_button.setText(QCoreApplication.translate("HalfCellInterface", u"Help", None))
        self.label_32.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>F(C/mol)</p></body></html>", None))
        self.label_33.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>r(m)</p></body></html>", None))
        self.label_35.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>D<span style=\" vertical-align:sub;\">s,WE</span>(m<span style=\" vertical-align:super;\">2</span>/s)</p></body></html>", None))
        self.label_36.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>k<span style=\" vertical-align:sub;\">react,WE</span>(m<span style=\" vertical-align:super;\">2.5</span>/(mol<span style=\" vertical-align:super;\">0.5</span>*s))</p></body></html>", None))
        self.label_45.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>k<span style=\" vertical-align:sub;\">react,RE</span>(m<span style=\" vertical-align:super;\">2.5</span>/(mol<span style=\" vertical-align:super;\">0.5</span>*s))</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("HalfCellInterface", u"Constant->", None))
        self.run_constant2_button.setText(QCoreApplication.translate("HalfCellInterface", u"Next", None))
        self.change_constant_button.setText(QCoreApplication.translate("HalfCellInterface", u"Modify", None))
        self.label_20.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>I<span style=\" vertical-align:sub;\">app</span>(A/m<span style=\" vertical-align:super;\">2</span>)</p></body></html>", None))
        self.label_38.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>alpha<span style=\" vertical-align:sub;\">C,WE</span></p></body></html>", None))
        self.select_discharge.setText(QCoreApplication.translate("HalfCellInterface", u"Discharge", None))
        self.groupBox.setTitle(QCoreApplication.translate("HalfCellInterface", u"Material", None))
        self.select_carbon.setText(QCoreApplication.translate("HalfCellInterface", u"Graphite", None))
        self.select_silicon.setText(QCoreApplication.translate("HalfCellInterface", u"Silicon", None))
        self.select_charge.setText(QCoreApplication.translate("HalfCellInterface", u"Charge", None))
        self.label_37.setText(QCoreApplication.translate("HalfCellInterface", u"alpha<sub>A,WE</sub>", None))
        self.label_47.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>alpha<span style=\" vertical-align:sub;\">A,RE</span></p></body></html>", None))
        self.label_48.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>alpha<span style=\" vertical-align:sub;\">C,RE</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("HalfCellInterface", u"Constant cont.", None))
        self.label_21.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>WE-ce(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.change_boundary_button.setText(QCoreApplication.translate("HalfCellInterface", u"Modify", None))
        self.run_boundary_button.setText(QCoreApplication.translate("HalfCellInterface", u"Next", None))
        self.label_39.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>WE-cs(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_40.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>WE-fai_e(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_41.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>WE-fai_s(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_42.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>sep-ce(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_43.setText(QCoreApplication.translate("HalfCellInterface", u"<html><head/><body><p>sep-fai_e(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("HalfCellInterface", u"Initial condition->", None))
        self.change_function_button.setText(QCoreApplication.translate("HalfCellInterface", u"Modify", None))
        self.run_function_button.setText(QCoreApplication.translate("HalfCellInterface", u"Next", None))
        self.label_22.setText(QCoreApplication.translate("HalfCellInterface", u"Time derivative ddt", None))
        self.label_23.setText(QCoreApplication.translate("HalfCellInterface", u"Gardient", None))
        self.label_24.setText(QCoreApplication.translate("HalfCellInterface", u"Divergence", None))
        self.label_25.setText(QCoreApplication.translate("HalfCellInterface", u"Laplacian", None))
        self.label_26.setText(QCoreApplication.translate("HalfCellInterface", u"Interpolation", None))
        self.interpolation_comboBox.setItemText(0, QCoreApplication.translate("HalfCellInterface", u"linear", None))
        self.interpolation_comboBox.setItemText(1, QCoreApplication.translate("HalfCellInterface", u"cubic", None))
        self.interpolation_comboBox.setItemText(2, QCoreApplication.translate("HalfCellInterface", u"none", None))

        self.laplacian_comboBox.setItemText(0, QCoreApplication.translate("HalfCellInterface", u"Gauss linear uncorrected", None))
        self.laplacian_comboBox.setItemText(1, QCoreApplication.translate("HalfCellInterface", u"Gauss linear corrected", None))
        self.laplacian_comboBox.setItemText(2, QCoreApplication.translate("HalfCellInterface", u"Gauss linear orthogonal", None))
        self.laplacian_comboBox.setItemText(3, QCoreApplication.translate("HalfCellInterface", u"none", None))

        self.gardient_comboBox.setItemText(0, QCoreApplication.translate("HalfCellInterface", u"Gauss linear", None))
        self.gardient_comboBox.setItemText(1, QCoreApplication.translate("HalfCellInterface", u"Gauss cubic", None))
        self.gardient_comboBox.setItemText(2, QCoreApplication.translate("HalfCellInterface", u"leastSquares", None))
        self.gardient_comboBox.setItemText(3, QCoreApplication.translate("HalfCellInterface", u"none", None))

        self.derivative_comboBox.setItemText(0, QCoreApplication.translate("HalfCellInterface", u"Euler", None))
        self.derivative_comboBox.setItemText(1, QCoreApplication.translate("HalfCellInterface", u"backward", None))
        self.derivative_comboBox.setItemText(2, QCoreApplication.translate("HalfCellInterface", u"localEuler", None))
        self.derivative_comboBox.setItemText(3, QCoreApplication.translate("HalfCellInterface", u"steadyState", None))
        self.derivative_comboBox.setItemText(4, QCoreApplication.translate("HalfCellInterface", u"none", None))

        self.divergence_comboBox.setItemText(0, QCoreApplication.translate("HalfCellInterface", u"bounded Gauss upwind", None))
        self.divergence_comboBox.setItemText(1, QCoreApplication.translate("HalfCellInterface", u"none", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("HalfCellInterface", u"Discretization->", None))
        self.label_27.setText(QCoreApplication.translate("HalfCellInterface", u"Tolerance", None))
        self.change_control_button.setText(QCoreApplication.translate("HalfCellInterface", u"Modify", None))
        self.label_28.setText(QCoreApplication.translate("HalfCellInterface", u"Endtime(s)", None))
        self.label_29.setText(QCoreApplication.translate("HalfCellInterface", u"Timestep(s)", None))
        self.label_30.setText(QCoreApplication.translate("HalfCellInterface", u"Write interval(No. of timesteps)", None))
        self.run_button.setText(QCoreApplication.translate("HalfCellInterface", u"Run/Resume", None))
        self.pause_run_button.setText(QCoreApplication.translate("HalfCellInterface", u"Pause", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("HalfCellInterface", u"Control", None))
        self.pushButton.setText(QCoreApplication.translate("HalfCellInterface", u"Execute", None))
        self.label_44.setText(QCoreApplication.translate("HalfCellInterface", u"View Geometry", None))
        self.open_paraview_Button.setText(QCoreApplication.translate("HalfCellInterface", u"View", None))
        self.view_result_button.setText(QCoreApplication.translate("HalfCellInterface", u"View", None))
        self.label_46.setText(QCoreApplication.translate("HalfCellInterface", u"View Results", None))
    # retranslateUi

