# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'carboninterface.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QGroupBox,
    QLabel, QLineEdit, QPushButton, QRadioButton,
    QSizePolicy, QTabWidget, QTextBrowser, QTextEdit,
    QWidget)

class Ui_CarbonInterface(object):
    def setupUi(self, CarbonInterface):
        if not CarbonInterface.objectName():
            CarbonInterface.setObjectName(u"CarbonInterface")
        CarbonInterface.resize(950, 640)
        self.c_back_Button = QPushButton(CarbonInterface)
        self.c_back_Button.setObjectName(u"c_back_Button")
        self.c_back_Button.setGeometry(QRect(830, 594, 91, 31))
        font = QFont()
        font.setPointSize(12)
        self.c_back_Button.setFont(font)
        self.textBrowser = QTextBrowser(CarbonInterface)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(0, 0, 410, 130))
        self.terminal_output_window = QTextEdit(CarbonInterface)
        self.terminal_output_window.setObjectName(u"terminal_output_window")
        self.terminal_output_window.setGeometry(QRect(0, 140, 410, 300))
        self.command_input_lineEdit = QLineEdit(CarbonInterface)
        self.command_input_lineEdit.setObjectName(u"command_input_lineEdit")
        self.command_input_lineEdit.setEnabled(True)
        self.command_input_lineEdit.setGeometry(QRect(10, 460, 241, 25))
        self.pushButton = QPushButton(CarbonInterface)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QRect(280, 460, 89, 25))
        self.tabWidget = QTabWidget(CarbonInterface)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(420, 0, 521, 581))
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.unit_select_box = QComboBox(self.tab)
        self.unit_select_box.addItem("")
        self.unit_select_box.addItem("")
        self.unit_select_box.addItem("")
        self.unit_select_box.setObjectName(u"unit_select_box")
        self.unit_select_box.setGeometry(QRect(20, 40, 161, 25))
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 10, 171, 21))
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(240, 130, 91, 17))
        self.length_lineEdit = QLineEdit(self.tab)
        self.length_lineEdit.setObjectName(u"length_lineEdit")
        self.length_lineEdit.setGeometry(QRect(20, 160, 81, 25))
        self.width_lineEdit = QLineEdit(self.tab)
        self.width_lineEdit.setObjectName(u"width_lineEdit")
        self.width_lineEdit.setGeometry(QRect(130, 160, 81, 25))
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(130, 130, 81, 17))
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 90, 271, 21))
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 130, 81, 17))
        self.height_lineEdit = QLineEdit(self.tab)
        self.height_lineEdit.setObjectName(u"height_lineEdit")
        self.height_lineEdit.setGeometry(QRect(240, 160, 81, 25))
        self.radius_lineEdit = QLineEdit(self.tab)
        self.radius_lineEdit.setObjectName(u"radius_lineEdit")
        self.radius_lineEdit.setGeometry(QRect(20, 250, 81, 25))
        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 210, 141, 21))
        self.z_divide_lineEdit = QLineEdit(self.tab)
        self.z_divide_lineEdit.setObjectName(u"z_divide_lineEdit")
        self.z_divide_lineEdit.setGeometry(QRect(280, 340, 81, 25))
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 340, 16, 17))
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 340, 16, 17))
        self.label_10 = QLabel(self.tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(260, 340, 16, 17))
        self.x_divide_lineEdit = QLineEdit(self.tab)
        self.x_divide_lineEdit.setObjectName(u"x_divide_lineEdit")
        self.x_divide_lineEdit.setGeometry(QRect(20, 340, 81, 25))
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 300, 271, 21))
        self.y_divide_lineEdit = QLineEdit(self.tab)
        self.y_divide_lineEdit.setObjectName(u"y_divide_lineEdit")
        self.y_divide_lineEdit.setGeometry(QRect(150, 340, 81, 25))
        self.change_geometry_button = QPushButton(self.tab)
        self.change_geometry_button.setObjectName(u"change_geometry_button")
        self.change_geometry_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_geometry_button = QPushButton(self.tab)
        self.run_geometry_button.setObjectName(u"run_geometry_button")
        self.run_geometry_button.setGeometry(QRect(410, 510, 89, 25))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 20, 181, 17))
        self.label_11.setFont(font)
        self.DS_lineEdit = QLineEdit(self.tab_2)
        self.DS_lineEdit.setObjectName(u"DS_lineEdit")
        self.DS_lineEdit.setGeometry(QRect(20, 50, 113, 25))
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 90, 201, 17))
        self.label_12.setFont(font)
        self.CS_lineEdit = QLineEdit(self.tab_2)
        self.CS_lineEdit.setObjectName(u"CS_lineEdit")
        self.CS_lineEdit.setGeometry(QRect(20, 120, 113, 25))
        self.label_13 = QLabel(self.tab_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 160, 211, 17))
        self.label_13.setFont(font)
        self.KReact_lineEdit = QLineEdit(self.tab_2)
        self.KReact_lineEdit.setObjectName(u"KReact_lineEdit")
        self.KReact_lineEdit.setGeometry(QRect(20, 190, 113, 25))
        self.label_14 = QLabel(self.tab_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 230, 131, 17))
        self.label_14.setFont(font)
        self.label_15 = QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 300, 111, 17))
        self.label_15.setFont(font)
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 370, 111, 17))
        self.label_16.setFont(font)
        self.R_lineEdit = QLineEdit(self.tab_2)
        self.R_lineEdit.setObjectName(u"R_lineEdit")
        self.R_lineEdit.setGeometry(QRect(20, 260, 113, 25))
        self.Ce_lineEdit = QLineEdit(self.tab_2)
        self.Ce_lineEdit.setObjectName(u"Ce_lineEdit")
        self.Ce_lineEdit.setGeometry(QRect(20, 400, 113, 25))
        self.F_lineEdit = QLineEdit(self.tab_2)
        self.F_lineEdit.setObjectName(u"F_lineEdit")
        self.F_lineEdit.setGeometry(QRect(20, 330, 113, 25))
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(270, 20, 101, 17))
        self.label_17.setFont(font)
        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(270, 90, 91, 17))
        self.label_18.setFont(font)
        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(270, 160, 101, 16))
        self.label_19.setFont(font)
        self.label_20 = QLabel(self.tab_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(270, 230, 111, 21))
        self.label_20.setFont(font)
        self.select_charge = QRadioButton(self.tab_2)
        self.select_charge.setObjectName(u"select_charge")
        self.select_charge.setGeometry(QRect(270, 260, 112, 23))
        self.select_discharge = QRadioButton(self.tab_2)
        self.select_discharge.setObjectName(u"select_discharge")
        self.select_discharge.setGeometry(QRect(270, 290, 112, 23))
        self.Temp_lineEdit = QLineEdit(self.tab_2)
        self.Temp_lineEdit.setObjectName(u"Temp_lineEdit")
        self.Temp_lineEdit.setGeometry(QRect(270, 190, 113, 25))
        self.I_lineEdit = QLineEdit(self.tab_2)
        self.I_lineEdit.setObjectName(u"I_lineEdit")
        self.I_lineEdit.setGeometry(QRect(270, 320, 113, 25))
        self.alphaC_lineEdit = QLineEdit(self.tab_2)
        self.alphaC_lineEdit.setObjectName(u"alphaC_lineEdit")
        self.alphaC_lineEdit.setGeometry(QRect(270, 120, 113, 25))
        self.alphaA_lineEdit = QLineEdit(self.tab_2)
        self.alphaA_lineEdit.setObjectName(u"alphaA_lineEdit")
        self.alphaA_lineEdit.setGeometry(QRect(270, 50, 113, 25))
        self.change_constant_button = QPushButton(self.tab_2)
        self.change_constant_button.setObjectName(u"change_constant_button")
        self.change_constant_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_constant_button = QPushButton(self.tab_2)
        self.run_constant_button.setObjectName(u"run_constant_button")
        self.run_constant_button.setGeometry(QRect(410, 510, 89, 25))
        self.help_constant_button = QPushButton(self.tab_2)
        self.help_constant_button.setObjectName(u"help_constant_button")
        self.help_constant_button.setGeometry(QRect(410, 430, 89, 25))
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(270, 360, 121, 101))
        self.select_carbon = QRadioButton(self.groupBox)
        self.select_carbon.setObjectName(u"select_carbon")
        self.select_carbon.setGeometry(QRect(10, 30, 112, 23))
        self.select_silicon = QRadioButton(self.groupBox)
        self.select_silicon.setObjectName(u"select_silicon")
        self.select_silicon.setGeometry(QRect(10, 70, 112, 23))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_21 = QLabel(self.tab_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 20, 401, 17))
        self.label_21.setFont(font)
        self.initial_cs_lineEdit = QLineEdit(self.tab_3)
        self.initial_cs_lineEdit.setObjectName(u"initial_cs_lineEdit")
        self.initial_cs_lineEdit.setGeometry(QRect(20, 50, 113, 25))
        self.change_boundary_button = QPushButton(self.tab_3)
        self.change_boundary_button.setObjectName(u"change_boundary_button")
        self.change_boundary_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_boundary_button = QPushButton(self.tab_3)
        self.run_boundary_button.setObjectName(u"run_boundary_button")
        self.run_boundary_button.setGeometry(QRect(410, 510, 89, 25))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.change_function_button = QPushButton(self.tab_4)
        self.change_function_button.setObjectName(u"change_function_button")
        self.change_function_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_function_button = QPushButton(self.tab_4)
        self.run_function_button.setObjectName(u"run_function_button")
        self.run_function_button.setGeometry(QRect(410, 510, 89, 25))
        self.label_22 = QLabel(self.tab_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 20, 171, 17))
        self.label_22.setFont(font)
        self.label_23 = QLabel(self.tab_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 110, 111, 17))
        self.label_23.setFont(font)
        self.label_24 = QLabel(self.tab_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 200, 141, 17))
        self.label_24.setFont(font)
        self.label_25 = QLabel(self.tab_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 290, 141, 17))
        self.label_25.setFont(font)
        self.label_26 = QLabel(self.tab_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 380, 171, 17))
        self.interpolation_comboBox = QComboBox(self.tab_4)
        self.interpolation_comboBox.addItem("")
        self.interpolation_comboBox.addItem("")
        self.interpolation_comboBox.addItem("")
        self.interpolation_comboBox.setObjectName(u"interpolation_comboBox")
        self.interpolation_comboBox.setGeometry(QRect(20, 410, 231, 25))
        self.laplacian_comboBox = QComboBox(self.tab_4)
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.setObjectName(u"laplacian_comboBox")
        self.laplacian_comboBox.setGeometry(QRect(20, 320, 231, 25))
        self.gardient_comboBox = QComboBox(self.tab_4)
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.setObjectName(u"gardient_comboBox")
        self.gardient_comboBox.setGeometry(QRect(20, 140, 231, 25))
        self.derivative_comboBox = QComboBox(self.tab_4)
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.setObjectName(u"derivative_comboBox")
        self.derivative_comboBox.setGeometry(QRect(20, 50, 231, 25))
        self.divergence_comboBox = QComboBox(self.tab_4)
        self.divergence_comboBox.addItem("")
        self.divergence_comboBox.addItem("")
        self.divergence_comboBox.setObjectName(u"divergence_comboBox")
        self.divergence_comboBox.setGeometry(QRect(20, 230, 231, 25))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_27 = QLabel(self.tab_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(30, 20, 101, 17))
        self.tolerance_lineEdit = QLineEdit(self.tab_5)
        self.tolerance_lineEdit.setObjectName(u"tolerance_lineEdit")
        self.tolerance_lineEdit.setGeometry(QRect(30, 50, 113, 25))
        self.change_control_button = QPushButton(self.tab_5)
        self.change_control_button.setObjectName(u"change_control_button")
        self.change_control_button.setGeometry(QRect(388, 440, 111, 25))
        self.label_28 = QLabel(self.tab_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(240, 20, 111, 17))
        self.endtime_lineEdit = QLineEdit(self.tab_5)
        self.endtime_lineEdit.setObjectName(u"endtime_lineEdit")
        self.endtime_lineEdit.setGeometry(QRect(240, 50, 113, 25))
        self.label_29 = QLabel(self.tab_5)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(240, 100, 131, 17))
        self.timestep_lineEdit = QLineEdit(self.tab_5)
        self.timestep_lineEdit.setObjectName(u"timestep_lineEdit")
        self.timestep_lineEdit.setGeometry(QRect(240, 130, 113, 25))
        self.label_30 = QLabel(self.tab_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(240, 180, 261, 17))
        self.interval_lineEdit = QLineEdit(self.tab_5)
        self.interval_lineEdit.setObjectName(u"interval_lineEdit")
        self.interval_lineEdit.setGeometry(QRect(240, 210, 113, 25))
        self.run_button = QPushButton(self.tab_5)
        self.run_button.setObjectName(u"run_button")
        self.run_button.setGeometry(QRect(388, 480, 111, 25))
        self.pause_run_button = QPushButton(self.tab_5)
        self.pause_run_button.setObjectName(u"pause_run_button")
        self.pause_run_button.setGeometry(QRect(388, 520, 111, 25))
        self.tabWidget.addTab(self.tab_5, "")
        self.label_32 = QLabel(CarbonInterface)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 540, 151, 17))
        self.open_paraview_Button = QPushButton(CarbonInterface)
        self.open_paraview_Button.setObjectName(u"open_paraview_Button")
        self.open_paraview_Button.setGeometry(QRect(170, 540, 89, 25))
        self.view_result_button = QPushButton(CarbonInterface)
        self.view_result_button.setObjectName(u"view_result_button")
        self.view_result_button.setEnabled(False)
        self.view_result_button.setGeometry(QRect(170, 590, 89, 25))
        self.label_33 = QLabel(CarbonInterface)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 590, 141, 17))

        self.retranslateUi(CarbonInterface)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(CarbonInterface)
    # setupUi

    def retranslateUi(self, CarbonInterface):
        CarbonInterface.setWindowTitle(QCoreApplication.translate("CarbonInterface", u"Dialog", None))
        self.c_back_Button.setText(QCoreApplication.translate("CarbonInterface", u"Home", None))
        self.textBrowser.setHtml(QCoreApplication.translate("CarbonInterface", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The modle you choose is <span style=\" font-weight:600;\">Single Particle Module</span>. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The initial values shown in the input boxes and select boxs are the current values in the files.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you are the first time to run this project, you must click <span style=\" font-weight:600;\">*Modify</span> button on Geom"
                        "etry interface at least once even if you do not change parameters on this interface. </p></body></html>", None))
        self.pushButton.setText(QCoreApplication.translate("CarbonInterface", u"Execute", None))
        self.unit_select_box.setItemText(0, QCoreApplication.translate("CarbonInterface", u"micrometer(um)", None))
        self.unit_select_box.setItemText(1, QCoreApplication.translate("CarbonInterface", u"millimeter(mm)", None))
        self.unit_select_box.setItemText(2, QCoreApplication.translate("CarbonInterface", u"meter(m)", None))

        self.label.setText(QCoreApplication.translate("CarbonInterface", u"Length unit", None))
        self.label_5.setText(QCoreApplication.translate("CarbonInterface", u"Height", None))
        self.label_4.setText(QCoreApplication.translate("CarbonInterface", u"Width", None))
        self.label_2.setText(QCoreApplication.translate("CarbonInterface", u"Computational domain", None))
        self.label_3.setText(QCoreApplication.translate("CarbonInterface", u"Length", None))
        self.label_6.setText(QCoreApplication.translate("CarbonInterface", u"Particle radius", None))
        self.label_8.setText(QCoreApplication.translate("CarbonInterface", u"X", None))
        self.label_9.setText(QCoreApplication.translate("CarbonInterface", u"Y", None))
        self.label_10.setText(QCoreApplication.translate("CarbonInterface", u"Z", None))
        self.label_7.setText(QCoreApplication.translate("CarbonInterface", u"Mesh settings", None))
        self.change_geometry_button.setText(QCoreApplication.translate("CarbonInterface", u"*Modify", None))
        self.run_geometry_button.setText(QCoreApplication.translate("CarbonInterface", u"Next", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("CarbonInterface", u"Geometry->", None))
        self.label_11.setText(QCoreApplication.translate("CarbonInterface", u"<html><head/><body><p>D<span style=\" vertical-align:sub;\">s</span> value(m<span style=\" vertical-align:super;\">2</span>/s)</p></body></html>", None))
        self.label_12.setText(QCoreApplication.translate("CarbonInterface", u"<html><head/><body><p>C<span style=\" vertical-align:sub;\">s</span> max(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("CarbonInterface", u"<html><head/><body><p>K<span style=\" vertical-align:sub;\">react</span>(m<span style=\" vertical-align:super;\">2.5</span>/(mol<span style=\" vertical-align:super;\">0.5</span>s))</p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("CarbonInterface", u"R(J/(mol*K))", None))
        self.label_15.setText(QCoreApplication.translate("CarbonInterface", u"F(C/mol)", None))
        self.label_16.setText(QCoreApplication.translate("CarbonInterface", u"<html><head/><body><p>C<span style=\" vertical-align:sub;\">e</span>(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_17.setText(QCoreApplication.translate("CarbonInterface", u"<html><head/><body><p>alpha<span style=\" vertical-align:sub;\">A</span></p></body></html>", None))
        self.label_18.setText(QCoreApplication.translate("CarbonInterface", u"alpha<sub>C</sub>", None))
        self.label_19.setText(QCoreApplication.translate("CarbonInterface", u"T(K)", None))
        self.label_20.setText(QCoreApplication.translate("CarbonInterface", u"<html><head/><body><p>I<span style=\" vertical-align:sub;\">app</span>(A/m<span style=\" vertical-align:super;\">2</span>)</p></body></html>", None))
        self.select_charge.setText(QCoreApplication.translate("CarbonInterface", u"Charge", None))
        self.select_discharge.setText(QCoreApplication.translate("CarbonInterface", u"Discharge", None))
        self.change_constant_button.setText(QCoreApplication.translate("CarbonInterface", u"Modify", None))
        self.run_constant_button.setText(QCoreApplication.translate("CarbonInterface", u"Next", None))
        self.help_constant_button.setText(QCoreApplication.translate("CarbonInterface", u"Help", None))
        self.groupBox.setTitle(QCoreApplication.translate("CarbonInterface", u"Material", None))
        self.select_carbon.setText(QCoreApplication.translate("CarbonInterface", u"Graphite", None))
        self.select_silicon.setText(QCoreApplication.translate("CarbonInterface", u"Silicon", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("CarbonInterface", u"Constant->", None))
        self.label_21.setText(QCoreApplication.translate("CarbonInterface", u"<html><head/><body><p>Initial electrode Li concentration(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.change_boundary_button.setText(QCoreApplication.translate("CarbonInterface", u"Modify", None))
        self.run_boundary_button.setText(QCoreApplication.translate("CarbonInterface", u"Next", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("CarbonInterface", u"Initial condition->", None))
        self.change_function_button.setText(QCoreApplication.translate("CarbonInterface", u"Modify", None))
        self.run_function_button.setText(QCoreApplication.translate("CarbonInterface", u"Next", None))
        self.label_22.setText(QCoreApplication.translate("CarbonInterface", u"Time derivative ddt", None))
        self.label_23.setText(QCoreApplication.translate("CarbonInterface", u"Gardient", None))
        self.label_24.setText(QCoreApplication.translate("CarbonInterface", u"Divergence", None))
        self.label_25.setText(QCoreApplication.translate("CarbonInterface", u"Laplacian", None))
        self.label_26.setText(QCoreApplication.translate("CarbonInterface", u"Interpolation", None))
        self.interpolation_comboBox.setItemText(0, QCoreApplication.translate("CarbonInterface", u"linear", None))
        self.interpolation_comboBox.setItemText(1, QCoreApplication.translate("CarbonInterface", u"cubic", None))
        self.interpolation_comboBox.setItemText(2, QCoreApplication.translate("CarbonInterface", u"none", None))

        self.laplacian_comboBox.setItemText(0, QCoreApplication.translate("CarbonInterface", u"Gauss linear uncorrected", None))
        self.laplacian_comboBox.setItemText(1, QCoreApplication.translate("CarbonInterface", u"Gauss linear corrected", None))
        self.laplacian_comboBox.setItemText(2, QCoreApplication.translate("CarbonInterface", u"Gauss linear orthogonal", None))
        self.laplacian_comboBox.setItemText(3, QCoreApplication.translate("CarbonInterface", u"none", None))

        self.gardient_comboBox.setItemText(0, QCoreApplication.translate("CarbonInterface", u"Gauss linear", None))
        self.gardient_comboBox.setItemText(1, QCoreApplication.translate("CarbonInterface", u"Gauss cubic", None))
        self.gardient_comboBox.setItemText(2, QCoreApplication.translate("CarbonInterface", u"leastSquares", None))
        self.gardient_comboBox.setItemText(3, QCoreApplication.translate("CarbonInterface", u"none", None))

        self.derivative_comboBox.setItemText(0, QCoreApplication.translate("CarbonInterface", u"Euler", None))
        self.derivative_comboBox.setItemText(1, QCoreApplication.translate("CarbonInterface", u"backward", None))
        self.derivative_comboBox.setItemText(2, QCoreApplication.translate("CarbonInterface", u"localEuler", None))
        self.derivative_comboBox.setItemText(3, QCoreApplication.translate("CarbonInterface", u"steadyState", None))
        self.derivative_comboBox.setItemText(4, QCoreApplication.translate("CarbonInterface", u"none", None))

        self.divergence_comboBox.setItemText(0, QCoreApplication.translate("CarbonInterface", u"bounded Gauss upwind", None))
        self.divergence_comboBox.setItemText(1, QCoreApplication.translate("CarbonInterface", u"none", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("CarbonInterface", u"Discretization->", None))
        self.label_27.setText(QCoreApplication.translate("CarbonInterface", u"Tolerance", None))
        self.change_control_button.setText(QCoreApplication.translate("CarbonInterface", u"Modify", None))
        self.label_28.setText(QCoreApplication.translate("CarbonInterface", u"Endtime(s)", None))
        self.label_29.setText(QCoreApplication.translate("CarbonInterface", u"Timestep(s)", None))
        self.label_30.setText(QCoreApplication.translate("CarbonInterface", u"Write interval(No. of timesteps)", None))
        self.run_button.setText(QCoreApplication.translate("CarbonInterface", u"Run/Resume", None))
        self.pause_run_button.setText(QCoreApplication.translate("CarbonInterface", u"Pause", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("CarbonInterface", u"Control", None))
        self.label_32.setText(QCoreApplication.translate("CarbonInterface", u"View Geometry", None))
        self.open_paraview_Button.setText(QCoreApplication.translate("CarbonInterface", u"View", None))
        self.view_result_button.setText(QCoreApplication.translate("CarbonInterface", u"View", None))
        self.label_33.setText(QCoreApplication.translate("CarbonInterface", u"View Results", None))
    # retranslateUi

