# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'fullcellfoam.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QGroupBox,
    QLabel, QLineEdit, QPushButton, QRadioButton,
    QSizePolicy, QTabWidget, QTextBrowser, QTextEdit,
    QWidget)

class Ui_FullCellFoam(object):
    def setupUi(self, FullCellFoam):
        if not FullCellFoam.objectName():
            FullCellFoam.setObjectName(u"FullCellFoam")
        FullCellFoam.resize(950, 640)
        self.tabWidget = QTabWidget(FullCellFoam)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(430, 0, 521, 581))
        font = QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.unit_select_box = QComboBox(self.tab)
        self.unit_select_box.addItem("")
        self.unit_select_box.addItem("")
        self.unit_select_box.addItem("")
        self.unit_select_box.setObjectName(u"unit_select_box")
        self.unit_select_box.setGeometry(QRect(20, 40, 161, 25))
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 10, 141, 21))
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(130, 200, 71, 17))
        self.length_lineEdit = QLineEdit(self.tab)
        self.length_lineEdit.setObjectName(u"length_lineEdit")
        self.length_lineEdit.setGeometry(QRect(10, 160, 81, 25))
        self.width_lineEdit = QLineEdit(self.tab)
        self.width_lineEdit.setObjectName(u"width_lineEdit")
        self.width_lineEdit.setGeometry(QRect(10, 230, 81, 25))
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 200, 61, 17))
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 90, 231, 17))
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 130, 91, 17))
        self.height_lineEdit = QLineEdit(self.tab)
        self.height_lineEdit.setObjectName(u"height_lineEdit")
        self.height_lineEdit.setGeometry(QRect(130, 230, 81, 25))
        self.length2_lineEdit = QLineEdit(self.tab)
        self.length2_lineEdit.setObjectName(u"length2_lineEdit")
        self.length2_lineEdit.setGeometry(QRect(130, 160, 81, 25))
        self.z_divide_lineEdit = QLineEdit(self.tab)
        self.z_divide_lineEdit.setObjectName(u"z_divide_lineEdit")
        self.z_divide_lineEdit.setGeometry(QRect(160, 380, 81, 25))
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 330, 16, 17))
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 380, 16, 17))
        self.label_10 = QLabel(self.tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(130, 380, 16, 17))
        self.x_divide_lineEdit = QLineEdit(self.tab)
        self.x_divide_lineEdit.setObjectName(u"x_divide_lineEdit")
        self.x_divide_lineEdit.setGeometry(QRect(30, 330, 81, 25))
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 290, 231, 17))
        self.y_divide_lineEdit = QLineEdit(self.tab)
        self.y_divide_lineEdit.setObjectName(u"y_divide_lineEdit")
        self.y_divide_lineEdit.setGeometry(QRect(30, 380, 81, 25))
        self.change_geometry_button = QPushButton(self.tab)
        self.change_geometry_button.setObjectName(u"change_geometry_button")
        self.change_geometry_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_geometry_button = QPushButton(self.tab)
        self.run_geometry_button.setObjectName(u"run_geometry_button")
        self.run_geometry_button.setGeometry(QRect(410, 510, 89, 25))
        self.label_31 = QLabel(self.tab)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(130, 130, 111, 17))
        self.label_34 = QLabel(self.tab)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(130, 330, 21, 17))
        self.x2_divide_lineEdit = QLineEdit(self.tab)
        self.x2_divide_lineEdit.setObjectName(u"x2_divide_lineEdit")
        self.x2_divide_lineEdit.setGeometry(QRect(160, 330, 81, 25))
        self.length3_lineEdit = QLineEdit(self.tab)
        self.length3_lineEdit.setObjectName(u"length3_lineEdit")
        self.length3_lineEdit.setGeometry(QRect(250, 160, 81, 25))
        self.label_44 = QLabel(self.tab)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(250, 130, 101, 17))
        self.label_45 = QLabel(self.tab)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(260, 330, 21, 17))
        self.x3_divide_lineEdit = QLineEdit(self.tab)
        self.x3_divide_lineEdit.setObjectName(u"x3_divide_lineEdit")
        self.x3_divide_lineEdit.setGeometry(QRect(290, 330, 81, 25))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 20, 191, 31))
        self.label_11.setFont(font)
        self.csmaxa_lineEdit = QLineEdit(self.tab_2)
        self.csmaxa_lineEdit.setObjectName(u"csmaxa_lineEdit")
        self.csmaxa_lineEdit.setGeometry(QRect(20, 50, 113, 25))
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 90, 201, 21))
        self.label_12.setFont(font)
        self.csmaxc_lineEdit = QLineEdit(self.tab_2)
        self.csmaxc_lineEdit.setObjectName(u"csmaxc_lineEdit")
        self.csmaxc_lineEdit.setGeometry(QRect(20, 120, 113, 25))
        self.label_13 = QLabel(self.tab_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 160, 221, 21))
        self.label_13.setFont(font)
        self.kreacta_lineEdit = QLineEdit(self.tab_2)
        self.kreacta_lineEdit.setObjectName(u"kreacta_lineEdit")
        self.kreacta_lineEdit.setGeometry(QRect(20, 190, 113, 25))
        self.label_14 = QLabel(self.tab_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 230, 221, 21))
        self.label_14.setFont(font)
        self.label_15 = QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 300, 161, 17))
        self.label_15.setFont(font)
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 370, 151, 21))
        self.label_16.setFont(font)
        self.kreactc_lineEdit = QLineEdit(self.tab_2)
        self.kreactc_lineEdit.setObjectName(u"kreactc_lineEdit")
        self.kreactc_lineEdit.setGeometry(QRect(20, 260, 113, 25))
        self.alphaca_lineEdit = QLineEdit(self.tab_2)
        self.alphaca_lineEdit.setObjectName(u"alphaca_lineEdit")
        self.alphaca_lineEdit.setGeometry(QRect(20, 400, 113, 25))
        self.alphaaa_lineEdit = QLineEdit(self.tab_2)
        self.alphaaa_lineEdit.setObjectName(u"alphaaa_lineEdit")
        self.alphaaa_lineEdit.setGeometry(QRect(20, 330, 113, 25))
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(250, 90, 121, 17))
        self.label_17.setFont(font)
        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(250, 160, 101, 21))
        self.label_18.setFont(font)
        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(250, 230, 121, 21))
        self.label_19.setFont(font)
        self.porcea_lineEdit = QLineEdit(self.tab_2)
        self.porcea_lineEdit.setObjectName(u"porcea_lineEdit")
        self.porcea_lineEdit.setGeometry(QRect(250, 260, 113, 25))
        self.f_lineEdit = QLineEdit(self.tab_2)
        self.f_lineEdit.setObjectName(u"f_lineEdit")
        self.f_lineEdit.setGeometry(QRect(250, 190, 113, 25))
        self.r_lineEdit = QLineEdit(self.tab_2)
        self.r_lineEdit.setObjectName(u"r_lineEdit")
        self.r_lineEdit.setGeometry(QRect(250, 120, 113, 25))
        self.help_constant_button = QPushButton(self.tab_2)
        self.help_constant_button.setObjectName(u"help_constant_button")
        self.help_constant_button.setGeometry(QRect(410, 470, 89, 25))
        self.alphaac_lineEdit = QLineEdit(self.tab_2)
        self.alphaac_lineEdit.setObjectName(u"alphaac_lineEdit")
        self.alphaac_lineEdit.setGeometry(QRect(20, 470, 113, 25))
        self.label_32 = QLabel(self.tab_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 440, 161, 21))
        self.label_32.setFont(font)
        self.porcesp_lineEdit = QLineEdit(self.tab_2)
        self.porcesp_lineEdit.setObjectName(u"porcesp_lineEdit")
        self.porcesp_lineEdit.setGeometry(QRect(250, 330, 113, 25))
        self.label_33 = QLabel(self.tab_2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(250, 300, 111, 21))
        self.label_33.setFont(font)
        self.porcec_lineEdit = QLineEdit(self.tab_2)
        self.porcec_lineEdit.setObjectName(u"porcec_lineEdit")
        self.porcec_lineEdit.setGeometry(QRect(250, 400, 113, 25))
        self.label_35 = QLabel(self.tab_2)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(250, 370, 121, 21))
        self.label_35.setFont(font)
        self.porfa_lineEdit = QLineEdit(self.tab_2)
        self.porfa_lineEdit.setObjectName(u"porfa_lineEdit")
        self.porfa_lineEdit.setGeometry(QRect(250, 470, 113, 25))
        self.label_36 = QLabel(self.tab_2)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(250, 440, 121, 21))
        self.label_36.setFont(font)
        self.constant_cont_button = QPushButton(self.tab_2)
        self.constant_cont_button.setObjectName(u"constant_cont_button")
        self.constant_cont_button.setGeometry(QRect(410, 510, 89, 25))
        self.label_54 = QLabel(self.tab_2)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(250, 20, 201, 21))
        self.label_54.setFont(font)
        self.alphacc_lineEdit = QLineEdit(self.tab_2)
        self.alphacc_lineEdit.setObjectName(u"alphacc_lineEdit")
        self.alphacc_lineEdit.setGeometry(QRect(250, 50, 113, 25))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.change_constant_button = QPushButton(self.tab_6)
        self.change_constant_button.setObjectName(u"change_constant_button")
        self.change_constant_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_constant_button = QPushButton(self.tab_6)
        self.run_constant_button.setObjectName(u"run_constant_button")
        self.run_constant_button.setGeometry(QRect(410, 510, 89, 25))
        self.select_discharge = QRadioButton(self.tab_6)
        self.select_discharge.setObjectName(u"select_discharge")
        self.select_discharge.setGeometry(QRect(210, 420, 112, 23))
        self.select_charge = QRadioButton(self.tab_6)
        self.select_charge.setObjectName(u"select_charge")
        self.select_charge.setGeometry(QRect(210, 390, 112, 23))
        self.label_38 = QLabel(self.tab_6)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 100, 111, 21))
        self.label_38.setFont(font)
        self.brugg_lineEdit = QLineEdit(self.tab_6)
        self.brugg_lineEdit.setObjectName(u"brugg_lineEdit")
        self.brugg_lineEdit.setGeometry(QRect(10, 130, 113, 25))
        self.label_20 = QLabel(self.tab_6)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(210, 360, 121, 21))
        self.label_20.setFont(font)
        self.I_lineEdit = QLineEdit(self.tab_6)
        self.I_lineEdit.setObjectName(u"I_lineEdit")
        self.I_lineEdit.setGeometry(QRect(210, 450, 113, 25))
        self.label_46 = QLabel(self.tab_6)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(10, 180, 151, 21))
        self.label_46.setFont(font)
        self.k0faisa_lineEdit = QLineEdit(self.tab_6)
        self.k0faisa_lineEdit.setObjectName(u"k0faisa_lineEdit")
        self.k0faisa_lineEdit.setGeometry(QRect(10, 210, 113, 25))
        self.label_47 = QLabel(self.tab_6)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(10, 270, 171, 21))
        self.label_47.setFont(font)
        self.k0faisc_lineEdit = QLineEdit(self.tab_6)
        self.k0faisc_lineEdit.setObjectName(u"k0faisc_lineEdit")
        self.k0faisc_lineEdit.setGeometry(QRect(10, 300, 113, 25))
        self.label_48 = QLabel(self.tab_6)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(10, 360, 171, 21))
        self.label_48.setFont(font)
        self.d0ce_lineEdit = QLineEdit(self.tab_6)
        self.d0ce_lineEdit.setObjectName(u"d0ce_lineEdit")
        self.d0ce_lineEdit.setGeometry(QRect(10, 390, 113, 25))
        self.label_49 = QLabel(self.tab_6)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(10, 450, 111, 21))
        self.label_49.setFont(font)
        self.tno_lineEdit = QLineEdit(self.tab_6)
        self.tno_lineEdit.setObjectName(u"tno_lineEdit")
        self.tno_lineEdit.setGeometry(QRect(10, 480, 113, 25))
        self.label_51 = QLabel(self.tab_6)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(210, 100, 111, 21))
        self.label_51.setFont(font)
        self.dsc_lineEdit = QLineEdit(self.tab_6)
        self.dsc_lineEdit.setObjectName(u"dsc_lineEdit")
        self.dsc_lineEdit.setGeometry(QRect(210, 130, 113, 25))
        self.label_52 = QLabel(self.tab_6)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(210, 180, 111, 21))
        self.label_52.setFont(font)
        self.rsa_lineEdit = QLineEdit(self.tab_6)
        self.rsa_lineEdit.setObjectName(u"rsa_lineEdit")
        self.rsa_lineEdit.setGeometry(QRect(210, 210, 113, 25))
        self.label_53 = QLabel(self.tab_6)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(210, 270, 111, 21))
        self.label_53.setFont(font)
        self.rsc_lineEdit = QLineEdit(self.tab_6)
        self.rsc_lineEdit.setObjectName(u"rsc_lineEdit")
        self.rsc_lineEdit.setGeometry(QRect(210, 300, 113, 25))
        self.label_37 = QLabel(self.tab_6)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 20, 111, 21))
        self.label_37.setFont(font)
        self.porfc_lineEdit = QLineEdit(self.tab_6)
        self.porfc_lineEdit.setObjectName(u"porfc_lineEdit")
        self.porfc_lineEdit.setGeometry(QRect(10, 50, 113, 25))
        self.label_50 = QLabel(self.tab_6)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(210, 20, 111, 21))
        self.label_50.setFont(font)
        self.dsa_lineEdit = QLineEdit(self.tab_6)
        self.dsa_lineEdit.setObjectName(u"dsa_lineEdit")
        self.dsa_lineEdit.setGeometry(QRect(210, 50, 113, 25))
        self.groupBox = QGroupBox(self.tab_6)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(360, 20, 131, 121))
        self.select_silicon = QRadioButton(self.groupBox)
        self.select_silicon.setObjectName(u"select_silicon")
        self.select_silicon.setGeometry(QRect(10, 80, 112, 23))
        self.select_carbon = QRadioButton(self.groupBox)
        self.select_carbon.setObjectName(u"select_carbon")
        self.select_carbon.setGeometry(QRect(10, 40, 112, 23))
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_21 = QLabel(self.tab_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 20, 161, 17))
        self.label_21.setFont(font)
        self.anode_ce_lineEdit = QLineEdit(self.tab_3)
        self.anode_ce_lineEdit.setObjectName(u"anode_ce_lineEdit")
        self.anode_ce_lineEdit.setGeometry(QRect(10, 50, 113, 25))
        self.change_boundary_button = QPushButton(self.tab_3)
        self.change_boundary_button.setObjectName(u"change_boundary_button")
        self.change_boundary_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_boundary_button = QPushButton(self.tab_3)
        self.run_boundary_button.setObjectName(u"run_boundary_button")
        self.run_boundary_button.setGeometry(QRect(410, 510, 89, 25))
        self.label_39 = QLabel(self.tab_3)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 110, 161, 17))
        self.label_39.setFont(font)
        self.anode_cs_lineEdit = QLineEdit(self.tab_3)
        self.anode_cs_lineEdit.setObjectName(u"anode_cs_lineEdit")
        self.anode_cs_lineEdit.setGeometry(QRect(10, 140, 113, 25))
        self.anode_faie_lineEdit = QLineEdit(self.tab_3)
        self.anode_faie_lineEdit.setObjectName(u"anode_faie_lineEdit")
        self.anode_faie_lineEdit.setGeometry(QRect(10, 230, 113, 25))
        self.label_40 = QLabel(self.tab_3)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 200, 171, 21))
        self.label_40.setFont(font)
        self.anode_fais_lineEdit = QLineEdit(self.tab_3)
        self.anode_fais_lineEdit.setObjectName(u"anode_fais_lineEdit")
        self.anode_fais_lineEdit.setGeometry(QRect(10, 320, 113, 25))
        self.label_41 = QLabel(self.tab_3)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 290, 171, 21))
        self.label_41.setFont(font)
        self.sep_ce_lineEdit = QLineEdit(self.tab_3)
        self.sep_ce_lineEdit.setObjectName(u"sep_ce_lineEdit")
        self.sep_ce_lineEdit.setGeometry(QRect(360, 50, 113, 25))
        self.label_42 = QLabel(self.tab_3)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(360, 20, 141, 17))
        self.label_42.setFont(font)
        self.sep_faie_lineEdit = QLineEdit(self.tab_3)
        self.sep_faie_lineEdit.setObjectName(u"sep_faie_lineEdit")
        self.sep_faie_lineEdit.setGeometry(QRect(360, 140, 113, 25))
        self.label_43 = QLabel(self.tab_3)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(360, 110, 151, 21))
        self.label_43.setFont(font)
        self.cathode_faie_lineEdit = QLineEdit(self.tab_3)
        self.cathode_faie_lineEdit.setObjectName(u"cathode_faie_lineEdit")
        self.cathode_faie_lineEdit.setGeometry(QRect(190, 230, 113, 25))
        self.label_55 = QLabel(self.tab_3)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(190, 290, 211, 21))
        self.label_55.setFont(font)
        self.label_56 = QLabel(self.tab_3)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(190, 110, 161, 17))
        self.label_56.setFont(font)
        self.cathode_fais_lineEdit = QLineEdit(self.tab_3)
        self.cathode_fais_lineEdit.setObjectName(u"cathode_fais_lineEdit")
        self.cathode_fais_lineEdit.setGeometry(QRect(190, 320, 113, 25))
        self.label_57 = QLabel(self.tab_3)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(190, 20, 161, 17))
        self.label_57.setFont(font)
        self.cathode_ce_lineEdit = QLineEdit(self.tab_3)
        self.cathode_ce_lineEdit.setObjectName(u"cathode_ce_lineEdit")
        self.cathode_ce_lineEdit.setGeometry(QRect(190, 50, 113, 25))
        self.label_58 = QLabel(self.tab_3)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(190, 200, 211, 21))
        self.label_58.setFont(font)
        self.cathode_cs_lineEdit = QLineEdit(self.tab_3)
        self.cathode_cs_lineEdit.setObjectName(u"cathode_cs_lineEdit")
        self.cathode_cs_lineEdit.setGeometry(QRect(190, 140, 113, 25))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.change_function_button = QPushButton(self.tab_4)
        self.change_function_button.setObjectName(u"change_function_button")
        self.change_function_button.setGeometry(QRect(410, 470, 89, 25))
        self.run_function_button = QPushButton(self.tab_4)
        self.run_function_button.setObjectName(u"run_function_button")
        self.run_function_button.setGeometry(QRect(410, 510, 89, 25))
        self.label_22 = QLabel(self.tab_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 20, 211, 17))
        self.label_22.setFont(font)
        self.label_23 = QLabel(self.tab_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 110, 131, 17))
        self.label_23.setFont(font)
        self.label_24 = QLabel(self.tab_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 200, 141, 17))
        self.label_24.setFont(font)
        self.label_25 = QLabel(self.tab_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 290, 131, 17))
        self.label_25.setFont(font)
        self.label_26 = QLabel(self.tab_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 380, 141, 17))
        self.interpolation_comboBox = QComboBox(self.tab_4)
        self.interpolation_comboBox.addItem("")
        self.interpolation_comboBox.addItem("")
        self.interpolation_comboBox.addItem("")
        self.interpolation_comboBox.setObjectName(u"interpolation_comboBox")
        self.interpolation_comboBox.setGeometry(QRect(20, 410, 221, 25))
        self.laplacian_comboBox = QComboBox(self.tab_4)
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.addItem("")
        self.laplacian_comboBox.setObjectName(u"laplacian_comboBox")
        self.laplacian_comboBox.setGeometry(QRect(20, 320, 221, 25))
        self.gardient_comboBox = QComboBox(self.tab_4)
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.addItem("")
        self.gardient_comboBox.setObjectName(u"gardient_comboBox")
        self.gardient_comboBox.setGeometry(QRect(20, 140, 221, 25))
        self.derivative_comboBox = QComboBox(self.tab_4)
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.addItem("")
        self.derivative_comboBox.setObjectName(u"derivative_comboBox")
        self.derivative_comboBox.setGeometry(QRect(20, 50, 221, 25))
        self.divergence_comboBox = QComboBox(self.tab_4)
        self.divergence_comboBox.addItem("")
        self.divergence_comboBox.addItem("")
        self.divergence_comboBox.setObjectName(u"divergence_comboBox")
        self.divergence_comboBox.setGeometry(QRect(20, 230, 221, 25))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_27 = QLabel(self.tab_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(30, 20, 101, 17))
        self.tolerance_lineEdit = QLineEdit(self.tab_5)
        self.tolerance_lineEdit.setObjectName(u"tolerance_lineEdit")
        self.tolerance_lineEdit.setGeometry(QRect(30, 50, 113, 25))
        self.change_control_button = QPushButton(self.tab_5)
        self.change_control_button.setObjectName(u"change_control_button")
        self.change_control_button.setGeometry(QRect(378, 440, 121, 25))
        self.label_28 = QLabel(self.tab_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(240, 20, 121, 17))
        self.endtime_lineEdit = QLineEdit(self.tab_5)
        self.endtime_lineEdit.setObjectName(u"endtime_lineEdit")
        self.endtime_lineEdit.setGeometry(QRect(240, 50, 113, 25))
        self.label_29 = QLabel(self.tab_5)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(240, 100, 131, 17))
        self.timestep_lineEdit = QLineEdit(self.tab_5)
        self.timestep_lineEdit.setObjectName(u"timestep_lineEdit")
        self.timestep_lineEdit.setGeometry(QRect(240, 130, 113, 25))
        self.label_30 = QLabel(self.tab_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(240, 180, 261, 17))
        self.interval_lineEdit = QLineEdit(self.tab_5)
        self.interval_lineEdit.setObjectName(u"interval_lineEdit")
        self.interval_lineEdit.setGeometry(QRect(240, 210, 113, 25))
        self.run_button = QPushButton(self.tab_5)
        self.run_button.setObjectName(u"run_button")
        self.run_button.setGeometry(QRect(378, 480, 121, 25))
        self.pause_run_button = QPushButton(self.tab_5)
        self.pause_run_button.setObjectName(u"pause_run_button")
        self.pause_run_button.setGeometry(QRect(378, 520, 121, 25))
        self.tabWidget.addTab(self.tab_5, "")
        self.terminal_output_window = QTextEdit(FullCellFoam)
        self.terminal_output_window.setObjectName(u"terminal_output_window")
        self.terminal_output_window.setGeometry(QRect(0, 140, 410, 300))
        self.pushButton = QPushButton(FullCellFoam)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(310, 460, 89, 25))
        self.textBrowser = QTextBrowser(FullCellFoam)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(0, 0, 410, 130))
        self.command_input_lineEdit = QLineEdit(FullCellFoam)
        self.command_input_lineEdit.setObjectName(u"command_input_lineEdit")
        self.command_input_lineEdit.setGeometry(QRect(0, 460, 291, 25))
        self.full_return_Button = QPushButton(FullCellFoam)
        self.full_return_Button.setObjectName(u"full_return_Button")
        self.full_return_Button.setGeometry(QRect(840, 590, 91, 31))
        self.full_return_Button.setFont(font)
        self.label_59 = QLabel(FullCellFoam)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(20, 540, 151, 17))
        self.open_paraview_Button = QPushButton(FullCellFoam)
        self.open_paraview_Button.setObjectName(u"open_paraview_Button")
        self.open_paraview_Button.setGeometry(QRect(180, 540, 89, 25))
        self.view_result_button = QPushButton(FullCellFoam)
        self.view_result_button.setObjectName(u"view_result_button")
        self.view_result_button.setEnabled(False)
        self.view_result_button.setGeometry(QRect(180, 580, 89, 25))
        self.label_61 = QLabel(FullCellFoam)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(20, 580, 141, 17))

        self.retranslateUi(FullCellFoam)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(FullCellFoam)
    # setupUi

    def retranslateUi(self, FullCellFoam):
        FullCellFoam.setWindowTitle(QCoreApplication.translate("FullCellFoam", u"Dialog", None))
        self.unit_select_box.setItemText(0, QCoreApplication.translate("FullCellFoam", u"micrometer(um)", None))
        self.unit_select_box.setItemText(1, QCoreApplication.translate("FullCellFoam", u"millimeter(mm)", None))
        self.unit_select_box.setItemText(2, QCoreApplication.translate("FullCellFoam", u"meter(m)", None))

        self.label.setText(QCoreApplication.translate("FullCellFoam", u"Length unit", None))
        self.label_5.setText(QCoreApplication.translate("FullCellFoam", u"Height", None))
        self.label_4.setText(QCoreApplication.translate("FullCellFoam", u"Width", None))
        self.label_2.setText(QCoreApplication.translate("FullCellFoam", u"Computational domain", None))
        self.label_3.setText(QCoreApplication.translate("FullCellFoam", u"Length_a", None))
        self.label_8.setText(QCoreApplication.translate("FullCellFoam", u"X", None))
        self.label_9.setText(QCoreApplication.translate("FullCellFoam", u"Y", None))
        self.label_10.setText(QCoreApplication.translate("FullCellFoam", u"Z", None))
        self.label_7.setText(QCoreApplication.translate("FullCellFoam", u"Mesh settings", None))
        self.change_geometry_button.setText(QCoreApplication.translate("FullCellFoam", u"*Modify", None))
        self.run_geometry_button.setText(QCoreApplication.translate("FullCellFoam", u"Next", None))
        self.label_31.setText(QCoreApplication.translate("FullCellFoam", u"Length_SEP", None))
        self.label_34.setText(QCoreApplication.translate("FullCellFoam", u"X2", None))
        self.label_44.setText(QCoreApplication.translate("FullCellFoam", u"Length_c", None))
        self.label_45.setText(QCoreApplication.translate("FullCellFoam", u"X3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("FullCellFoam", u"Geometry->", None))
        self.label_11.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>C<span style=\" vertical-align:sub;\">sa,max</span>(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_12.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>C<span style=\" vertical-align:sub;\">sc,max</span>(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>k<span style=\" vertical-align:sub;\">react,a</span>(m<span style=\" vertical-align:super;\">2.5</span>/(mol<span style=\" vertical-align:super;\">0.5</span>*s))</p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>k<span style=\" vertical-align:sub;\">react,c</span>(m<span style=\" vertical-align:super;\">2.5</span>/(mol<span style=\" vertical-align:super;\">0.5</span>*s))</p></body></html>", None))
        self.label_15.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>alpha<span style=\" vertical-align:sub;\">A</span>(anode)</p></body></html>", None))
        self.label_16.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>alpha<span style=\" vertical-align:sub;\">C</span>(anode)</p></body></html>", None))
        self.label_17.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>R(J/(mol*K))</p></body></html>", None))
        self.label_18.setText(QCoreApplication.translate("FullCellFoam", u"F(C/mol)", None))
        self.label_19.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>por<span style=\" vertical-align:sub;\">a</span></p></body></html>", None))
        self.help_constant_button.setText(QCoreApplication.translate("FullCellFoam", u"Help", None))
        self.label_32.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>alpha<span style=\" vertical-align:sub;\">A</span>(cathode)</p></body></html>", None))
        self.label_33.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>por<span style=\" vertical-align:sub;\">SEP</span></p></body></html>", None))
        self.label_35.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>por<span style=\" vertical-align:sub;\">c</span></p></body></html>", None))
        self.label_36.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>por<span style=\" vertical-align:sub;\">f,a</span></p></body></html>", None))
        self.constant_cont_button.setText(QCoreApplication.translate("FullCellFoam", u"Cont.", None))
        self.label_54.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>alpha<span style=\" vertical-align:sub;\">C</span>(cathode)</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("FullCellFoam", u"Constant->", None))
        self.change_constant_button.setText(QCoreApplication.translate("FullCellFoam", u"Modify", None))
        self.run_constant_button.setText(QCoreApplication.translate("FullCellFoam", u"Next", None))
        self.select_discharge.setText(QCoreApplication.translate("FullCellFoam", u"Discharge", None))
        self.select_charge.setText(QCoreApplication.translate("FullCellFoam", u"Charge", None))
        self.label_38.setText(QCoreApplication.translate("FullCellFoam", u"brugg", None))
        self.label_20.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>I<span style=\" vertical-align:sub;\">app</span>(A/m<span style=\" vertical-align:super;\">2</span>)</p></body></html>", None))
        self.label_46.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>k<span style=\" vertical-align:sub;\">0,a</span>(s/m)</p></body></html>", None))
        self.label_47.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>k<span style=\" vertical-align:sub;\">0,c</span>(s/m)</p></body></html>", None))
        self.label_48.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>D<span style=\" vertical-align:sub;\">0,e</span>(m<span style=\" vertical-align:super;\">2</span>/s)</p></body></html>", None))
        self.label_49.setText(QCoreApplication.translate("FullCellFoam", u"tNo", None))
        self.label_51.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>D<span style=\" vertical-align:sub;\">s,c</span>(m<span style=\" vertical-align:super;\">2</span>/s)</p></body></html>", None))
        self.label_52.setText(QCoreApplication.translate("FullCellFoam", u"r<sub>a</sub>(m)", None))
        self.label_53.setText(QCoreApplication.translate("FullCellFoam", u"r<sub>c</sub>(m)", None))
        self.label_37.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>por<span style=\" vertical-align:sub;\">f,c</span></p></body></html>", None))
        self.label_50.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>D<span style=\" vertical-align:sub;\">s,a</span>(m<span style=\" vertical-align:super;\">2</span>/s)</p></body></html>", None))
        self.groupBox.setTitle(QCoreApplication.translate("FullCellFoam", u"Anode Material", None))
        self.select_silicon.setText(QCoreApplication.translate("FullCellFoam", u"Silicon", None))
        self.select_carbon.setText(QCoreApplication.translate("FullCellFoam", u"Graphite", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("FullCellFoam", u"Constant cont.->", None))
        self.label_21.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>anode-ce(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.change_boundary_button.setText(QCoreApplication.translate("FullCellFoam", u"Modify", None))
        self.run_boundary_button.setText(QCoreApplication.translate("FullCellFoam", u"Next", None))
        self.label_39.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>anode-cs(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_40.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>anode-fai_e(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_41.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>anode-fai_s(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_42.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>sep-ce(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_43.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>sep-fai_e(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_55.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>cathode-fai_s(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_56.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>cathode-cs(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_57.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>cathode-ce(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_58.setText(QCoreApplication.translate("FullCellFoam", u"<html><head/><body><p>cathode-fai_e(mol/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("FullCellFoam", u"Initial condition->", None))
        self.change_function_button.setText(QCoreApplication.translate("FullCellFoam", u"Modify", None))
        self.run_function_button.setText(QCoreApplication.translate("FullCellFoam", u"Next", None))
        self.label_22.setText(QCoreApplication.translate("FullCellFoam", u"Time derivative ddt", None))
        self.label_23.setText(QCoreApplication.translate("FullCellFoam", u"Gardient", None))
        self.label_24.setText(QCoreApplication.translate("FullCellFoam", u"Divergence", None))
        self.label_25.setText(QCoreApplication.translate("FullCellFoam", u"Laplacian", None))
        self.label_26.setText(QCoreApplication.translate("FullCellFoam", u"Interpolation", None))
        self.interpolation_comboBox.setItemText(0, QCoreApplication.translate("FullCellFoam", u"linear", None))
        self.interpolation_comboBox.setItemText(1, QCoreApplication.translate("FullCellFoam", u"cubic", None))
        self.interpolation_comboBox.setItemText(2, QCoreApplication.translate("FullCellFoam", u"none", None))

        self.laplacian_comboBox.setItemText(0, QCoreApplication.translate("FullCellFoam", u"Gauss linear uncorrected", None))
        self.laplacian_comboBox.setItemText(1, QCoreApplication.translate("FullCellFoam", u"Gauss linear corrected", None))
        self.laplacian_comboBox.setItemText(2, QCoreApplication.translate("FullCellFoam", u"Gauss linear orthogonal", None))
        self.laplacian_comboBox.setItemText(3, QCoreApplication.translate("FullCellFoam", u"none", None))

        self.gardient_comboBox.setItemText(0, QCoreApplication.translate("FullCellFoam", u"Gauss linear", None))
        self.gardient_comboBox.setItemText(1, QCoreApplication.translate("FullCellFoam", u"Gauss cubic", None))
        self.gardient_comboBox.setItemText(2, QCoreApplication.translate("FullCellFoam", u"leastSquares", None))
        self.gardient_comboBox.setItemText(3, QCoreApplication.translate("FullCellFoam", u"none", None))

        self.derivative_comboBox.setItemText(0, QCoreApplication.translate("FullCellFoam", u"Euler", None))
        self.derivative_comboBox.setItemText(1, QCoreApplication.translate("FullCellFoam", u"backward", None))
        self.derivative_comboBox.setItemText(2, QCoreApplication.translate("FullCellFoam", u"localEuler", None))
        self.derivative_comboBox.setItemText(3, QCoreApplication.translate("FullCellFoam", u"steadyState", None))
        self.derivative_comboBox.setItemText(4, QCoreApplication.translate("FullCellFoam", u"none", None))

        self.divergence_comboBox.setItemText(0, QCoreApplication.translate("FullCellFoam", u"bounded Gauss upwind", None))
        self.divergence_comboBox.setItemText(1, QCoreApplication.translate("FullCellFoam", u"none", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("FullCellFoam", u"Discretization->", None))
        self.label_27.setText(QCoreApplication.translate("FullCellFoam", u"Tolerance", None))
        self.change_control_button.setText(QCoreApplication.translate("FullCellFoam", u"Modify", None))
        self.label_28.setText(QCoreApplication.translate("FullCellFoam", u"Endtime(s)", None))
        self.label_29.setText(QCoreApplication.translate("FullCellFoam", u"Timestep(s)", None))
        self.label_30.setText(QCoreApplication.translate("FullCellFoam", u"Write interval(No. of timesteps)", None))
        self.run_button.setText(QCoreApplication.translate("FullCellFoam", u"Run/Resume", None))
        self.pause_run_button.setText(QCoreApplication.translate("FullCellFoam", u"Pause", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("FullCellFoam", u"Control", None))
        self.pushButton.setText(QCoreApplication.translate("FullCellFoam", u"Execute", None))
        self.textBrowser.setHtml(QCoreApplication.translate("FullCellFoam", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The module you choose is <span style=\" font-weight:600;\">FullCell</span>. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The initial values shown in the input boxes and select boxs are the current values in the files.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you are the first time to run this project, you must click <span style=\" font-weight:600;\">*Modify</span> button on Geometry interfac"
                        "e at least once even if you do not change parameters on this interface. </p></body></html>", None))
        self.full_return_Button.setText(QCoreApplication.translate("FullCellFoam", u"Home", None))
        self.label_59.setText(QCoreApplication.translate("FullCellFoam", u"View Geometry", None))
        self.open_paraview_Button.setText(QCoreApplication.translate("FullCellFoam", u"View", None))
        self.view_result_button.setText(QCoreApplication.translate("FullCellFoam", u"View", None))
        self.label_61.setText(QCoreApplication.translate("FullCellFoam", u"View Results", None))
    # retranslateUi

